[redlib]
src.git = "https://github.com/redlib-org/redlib"
fetch.github = "redlib-org/redlib"
cargo_locks = [ "Cargo.lock" ]
# extract = [ "Cargo.lock" ]

[cross-seed]
src.git = "https://github.com/cross-seed/cross-seed"
fetch.github = "cross-seed/cross-seed"

[gamescope]
src.git = "https://github.com/ValveSoftware/gamescope"
fetch.github = "ValveSoftware/gamescope"
git.fetchSubmodules = true

[catppuccin-fish]
src.git = "https://github.com/catppuccin/fish"
fetch.github = "catppuccin/fish"

[catppuccin-gitea]
src.github = "catppuccin/gitea"
fetch.tarball = "https://github.com/catppuccin/gitea/releases/download/$ver/catppuccin-gitea.tar.gz"
